project_id = "bhkkauanozuwpxhukrha"

[functions.get-menus]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.payments-webhook]
verify_jwt = false

[functions.tts-jobs]
verify_jwt = true

[functions.tts-callback]
verify_jwt = false