// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhkkauanozuwpxhukrha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoa2thdWFub3p1d3B4aHVrcmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODM2NDYsImV4cCI6MjA3MjE1OTY0Nn0.eYPFWTKrzFKi1m9kpAntfmecV4aKsGCeTlNlKYawMJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});